# Cash In Hand Mutations - Write operations for Cash In Hand

mutation CashInHandInsert(
  $id: String!
  $date: String!
  $company: String!
  $mainCategory: String!
  $subCategory: String!
  $amount: Float!
  $mode: String!
  $note: String
) @auth(level: PUBLIC) {
  cashInHand_insert(
    data: {
      id: $id
      date: $date
      company: $company
      mainCategory: $mainCategory
      subCategory: $subCategory
      amount: $amount
      mode: $mode
      note: $note
      createdAt: "now()"
    }
  )
}

mutation CashInHandDelete($id: String!) @auth(level: PUBLIC) {
  cashInHand_delete(id: $id)
}
