# Bank Transfer Mutations - Write operations for Bank Transfers

mutation TransferInsert(
  $id: String!
  $date: String!
  $fromBankId: String!
  $fromBankName: String!
  $toBankId: String!
  $toBankName: String!
  $amount: Float!
  $note: String
) @auth(level: PUBLIC) {
  bankTransfer_insert(
    data: {
      id: $id
      date: $date
      fromBankId: $fromBankId
      fromBankName: $fromBankName
      toBankId: $toBankId
      toBankName: $toBankName
      amount: $amount
      note: $note
      createdAt: "now()"
    }
  )
}

mutation TransferDelete($id: String!) @auth(level: PUBLIC) {
  bankTransfer_delete(id: $id)
}
