# Budget Queries - Read operations for Budget

query listBudgets($limit: Int = 10, $offset: Int = 0) @auth(level: PUBLIC) {
  budgets(orderBy: { createdAt: DESC }, limit: $limit, offset: $offset) {
    id
    category
    subCategory
    period
    budgetLimit
    spent
    createdAt
    updatedAt
  }
}

query getBudgetById($id: String!) @auth(level: PUBLIC) {
  budget(id: $id) {
    id
    category
    subCategory
    period
    budgetLimit
    spent
    createdAt
    updatedAt
  }
}
