# Employee Queries

query ListEmployees(
  $limit: Int = 100
  $offset: Int = 0
) @auth(level: PUBLIC) {
  employees(limit: $limit, offset: $offset) {
    id
    name
    position
    salary
    phone
    email
    joinDate
    status
    location
    accountNumber
    bankName
    accountTitle
    createdAt
    updatedAt
  }
}

query GetEmployeeById($id: String!) @auth(level: PUBLIC) {
  employee(id: $id) {
    id
    name
    position
    salary
    phone
    email
    joinDate
    status
    location
    accountNumber
    bankName
    accountTitle
    createdAt
    updatedAt
  }
}
