extend type Mutation {
  """
  ✨ Insert a single `Bank` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  bank_insert(
    """
    Data object to insert into the table.
    """
    data: Bank_Data!
  ): Bank_KeyOutput! @fdc_generated(from: "Bank", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `BankTransfer` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  bankTransfer_insert(
    """
    Data object to insert into the table.
    """
    data: BankTransfer_Data!
  ): BankTransfer_KeyOutput! @fdc_generated(from: "BankTransfer", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Brand` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  brand_insert(
    """
    Data object to insert into the table.
    """
    data: Brand_Data!
  ): Brand_KeyOutput! @fdc_generated(from: "Brand", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Budget` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  budget_insert(
    """
    Data object to insert into the table.
    """
    data: Budget_Data!
  ): Budget_KeyOutput! @fdc_generated(from: "Budget", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `CashInHand` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  cashInHand_insert(
    """
    Data object to insert into the table.
    """
    data: CashInHand_Data!
  ): CashInHand_KeyOutput! @fdc_generated(from: "CashInHand", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Employee` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  employee_insert(
    """
    Data object to insert into the table.
    """
    data: Employee_Data!
  ): Employee_KeyOutput! @fdc_generated(from: "Employee", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Loan` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  loan_insert(
    """
    Data object to insert into the table.
    """
    data: Loan_Data!
  ): Loan_KeyOutput! @fdc_generated(from: "Loan", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `LoanPayment` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  loanPayment_insert(
    """
    Data object to insert into the table.
    """
    data: LoanPayment_Data!
  ): LoanPayment_KeyOutput! @fdc_generated(from: "LoanPayment", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Model` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  model_insert(
    """
    Data object to insert into the table.
    """
    data: Model_Data!
  ): Model_KeyOutput! @fdc_generated(from: "Model", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Product` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  product_insert(
    """
    Data object to insert into the table.
    """
    data: Product_Data!
  ): Product_KeyOutput! @fdc_generated(from: "Product", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ProductTransfer` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  productTransfer_insert(
    """
    Data object to insert into the table.
    """
    data: ProductTransfer_Data!
  ): ProductTransfer_KeyOutput! @fdc_generated(from: "ProductTransfer", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Bank` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  bank_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Bank_Data!]!
  ): [Bank_KeyOutput!]! @fdc_generated(from: "Bank", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `BankTransfer` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  bankTransfer_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [BankTransfer_Data!]!
  ): [BankTransfer_KeyOutput!]! @fdc_generated(from: "BankTransfer", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Brand` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  brand_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Brand_Data!]!
  ): [Brand_KeyOutput!]! @fdc_generated(from: "Brand", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Budget` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  budget_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Budget_Data!]!
  ): [Budget_KeyOutput!]! @fdc_generated(from: "Budget", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `CashInHand` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  cashInHand_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [CashInHand_Data!]!
  ): [CashInHand_KeyOutput!]! @fdc_generated(from: "CashInHand", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Employee` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  employee_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Employee_Data!]!
  ): [Employee_KeyOutput!]! @fdc_generated(from: "Employee", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Loan` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  loan_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Loan_Data!]!
  ): [Loan_KeyOutput!]! @fdc_generated(from: "Loan", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `LoanPayment` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  loanPayment_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [LoanPayment_Data!]!
  ): [LoanPayment_KeyOutput!]! @fdc_generated(from: "LoanPayment", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Model` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  model_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Model_Data!]!
  ): [Model_KeyOutput!]! @fdc_generated(from: "Model", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Product` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  product_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Product_Data!]!
  ): [Product_KeyOutput!]! @fdc_generated(from: "Product", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ProductTransfer` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  productTransfer_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ProductTransfer_Data!]!
  ): [ProductTransfer_KeyOutput!]! @fdc_generated(from: "ProductTransfer", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Bank` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Bank`.
  """
  bank_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Bank_Data!
  ): Bank_KeyOutput! @fdc_generated(from: "Bank", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `BankTransfer` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `BankTransfer`.
  """
  bankTransfer_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: BankTransfer_Data!
  ): BankTransfer_KeyOutput! @fdc_generated(from: "BankTransfer", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Brand` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Brand`.
  """
  brand_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Brand_Data!
  ): Brand_KeyOutput! @fdc_generated(from: "Brand", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Budget` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Budget`.
  """
  budget_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Budget_Data!
  ): Budget_KeyOutput! @fdc_generated(from: "Budget", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `CashInHand` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CashInHand`.
  """
  cashInHand_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: CashInHand_Data!
  ): CashInHand_KeyOutput! @fdc_generated(from: "CashInHand", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Employee` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Employee`.
  """
  employee_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Employee_Data!
  ): Employee_KeyOutput! @fdc_generated(from: "Employee", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Loan` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Loan`.
  """
  loan_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Loan_Data!
  ): Loan_KeyOutput! @fdc_generated(from: "Loan", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `LoanPayment` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LoanPayment`.
  """
  loanPayment_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: LoanPayment_Data!
  ): LoanPayment_KeyOutput! @fdc_generated(from: "LoanPayment", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Model` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Model`.
  """
  model_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Model_Data!
  ): Model_KeyOutput! @fdc_generated(from: "Model", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Product` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Product`.
  """
  product_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Product_Data!
  ): Product_KeyOutput! @fdc_generated(from: "Product", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ProductTransfer` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ProductTransfer`.
  """
  productTransfer_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ProductTransfer_Data!
  ): ProductTransfer_KeyOutput! @fdc_generated(from: "ProductTransfer", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Bank` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Bank`.
  """
  bank_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Bank_Data!]!
  ): [Bank_KeyOutput!]! @fdc_generated(from: "Bank", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `BankTransfer` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `BankTransfer`.
  """
  bankTransfer_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [BankTransfer_Data!]!
  ): [BankTransfer_KeyOutput!]! @fdc_generated(from: "BankTransfer", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Brand` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Brand`.
  """
  brand_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Brand_Data!]!
  ): [Brand_KeyOutput!]! @fdc_generated(from: "Brand", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Budget` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Budget`.
  """
  budget_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Budget_Data!]!
  ): [Budget_KeyOutput!]! @fdc_generated(from: "Budget", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `CashInHand` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CashInHand`.
  """
  cashInHand_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [CashInHand_Data!]!
  ): [CashInHand_KeyOutput!]! @fdc_generated(from: "CashInHand", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Employee` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Employee`.
  """
  employee_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Employee_Data!]!
  ): [Employee_KeyOutput!]! @fdc_generated(from: "Employee", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Loan` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Loan`.
  """
  loan_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Loan_Data!]!
  ): [Loan_KeyOutput!]! @fdc_generated(from: "Loan", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `LoanPayment` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LoanPayment`.
  """
  loanPayment_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [LoanPayment_Data!]!
  ): [LoanPayment_KeyOutput!]! @fdc_generated(from: "LoanPayment", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Model` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Model`.
  """
  model_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Model_Data!]!
  ): [Model_KeyOutput!]! @fdc_generated(from: "Model", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Product` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Product`.
  """
  product_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Product_Data!]!
  ): [Product_KeyOutput!]! @fdc_generated(from: "Product", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ProductTransfer` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ProductTransfer`.
  """
  productTransfer_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ProductTransfer_Data!]!
  ): [ProductTransfer_KeyOutput!]! @fdc_generated(from: "ProductTransfer", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Bank` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Bank` or `null` if not found.
  """
  bank_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Bank_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Bank_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Bank_Data!
  ): Bank_KeyOutput @fdc_generated(from: "Bank", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `BankTransfer` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `BankTransfer` or `null` if not found.
  """
  bankTransfer_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: BankTransfer_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: BankTransfer_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: BankTransfer_Data!
  ): BankTransfer_KeyOutput @fdc_generated(from: "BankTransfer", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Brand` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Brand` or `null` if not found.
  """
  brand_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Brand_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Brand_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Brand_Data!
  ): Brand_KeyOutput @fdc_generated(from: "Brand", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Budget` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Budget` or `null` if not found.
  """
  budget_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Budget_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Budget_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Budget_Data!
  ): Budget_KeyOutput @fdc_generated(from: "Budget", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `CashInHand` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `CashInHand` or `null` if not found.
  """
  cashInHand_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: CashInHand_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CashInHand_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: CashInHand_Data!
  ): CashInHand_KeyOutput @fdc_generated(from: "CashInHand", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Employee` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Employee` or `null` if not found.
  """
  employee_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Employee_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Employee_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Employee_Data!
  ): Employee_KeyOutput @fdc_generated(from: "Employee", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Loan` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Loan` or `null` if not found.
  """
  loan_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Loan_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Loan_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Loan_Data!
  ): Loan_KeyOutput @fdc_generated(from: "Loan", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `LoanPayment` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `LoanPayment` or `null` if not found.
  """
  loanPayment_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: LoanPayment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LoanPayment_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: LoanPayment_Data!
  ): LoanPayment_KeyOutput @fdc_generated(from: "LoanPayment", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Model` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Model` or `null` if not found.
  """
  model_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Model_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Model_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Model_Data!
  ): Model_KeyOutput @fdc_generated(from: "Model", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Product` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Product` or `null` if not found.
  """
  product_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Product_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Product_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Product_Data!
  ): Product_KeyOutput @fdc_generated(from: "Product", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ProductTransfer` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ProductTransfer` or `null` if not found.
  """
  productTransfer_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: ProductTransfer_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProductTransfer_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ProductTransfer_Data!
  ): ProductTransfer_KeyOutput @fdc_generated(from: "ProductTransfer", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Bank` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  bank_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Bank_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Bank_Data!
  ): Int! @fdc_generated(from: "Bank", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `BankTransfer` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  bankTransfer_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: BankTransfer_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: BankTransfer_Data!
  ): Int! @fdc_generated(from: "BankTransfer", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Brand` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  brand_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Brand_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Brand_Data!
  ): Int! @fdc_generated(from: "Brand", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Budget` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  budget_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Budget_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Budget_Data!
  ): Int! @fdc_generated(from: "Budget", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `CashInHand` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  cashInHand_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: CashInHand_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: CashInHand_Data!
  ): Int! @fdc_generated(from: "CashInHand", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Employee` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  employee_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Employee_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Employee_Data!
  ): Int! @fdc_generated(from: "Employee", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Loan` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  loan_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Loan_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Loan_Data!
  ): Int! @fdc_generated(from: "Loan", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `LoanPayment` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  loanPayment_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: LoanPayment_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: LoanPayment_Data!
  ): Int! @fdc_generated(from: "LoanPayment", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Model` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  model_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Model_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Model_Data!
  ): Int! @fdc_generated(from: "Model", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Product` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  product_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Product_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Product_Data!
  ): Int! @fdc_generated(from: "Product", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ProductTransfer` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  productTransfer_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ProductTransfer_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ProductTransfer_Data!
  ): Int! @fdc_generated(from: "ProductTransfer", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Bank` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  bank_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Bank_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Bank_FirstRow
  ): Bank_KeyOutput @fdc_generated(from: "Bank", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `BankTransfer` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  bankTransfer_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: BankTransfer_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: BankTransfer_FirstRow
  ): BankTransfer_KeyOutput @fdc_generated(from: "BankTransfer", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Brand` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  brand_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Brand_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Brand_FirstRow
  ): Brand_KeyOutput @fdc_generated(from: "Brand", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Budget` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  budget_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Budget_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Budget_FirstRow
  ): Budget_KeyOutput @fdc_generated(from: "Budget", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `CashInHand` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  cashInHand_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: CashInHand_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CashInHand_FirstRow
  ): CashInHand_KeyOutput @fdc_generated(from: "CashInHand", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Employee` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  employee_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Employee_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Employee_FirstRow
  ): Employee_KeyOutput @fdc_generated(from: "Employee", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Loan` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  loan_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Loan_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Loan_FirstRow
  ): Loan_KeyOutput @fdc_generated(from: "Loan", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `LoanPayment` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  loanPayment_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: LoanPayment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LoanPayment_FirstRow
  ): LoanPayment_KeyOutput @fdc_generated(from: "LoanPayment", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Model` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  model_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Model_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Model_FirstRow
  ): Model_KeyOutput @fdc_generated(from: "Model", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Product` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  product_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Product_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Product_FirstRow
  ): Product_KeyOutput @fdc_generated(from: "Product", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ProductTransfer` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  productTransfer_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: ProductTransfer_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProductTransfer_FirstRow
  ): ProductTransfer_KeyOutput @fdc_generated(from: "ProductTransfer", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Bank` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  bank_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Bank_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Bank", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `BankTransfer` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  bankTransfer_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: BankTransfer_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "BankTransfer", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Brand` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  brand_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Brand_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Brand", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Budget` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  budget_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Budget_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Budget", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `CashInHand` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  cashInHand_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: CashInHand_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "CashInHand", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Employee` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  employee_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Employee_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Employee", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Loan` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  loan_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Loan_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Loan", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `LoanPayment` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  loanPayment_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: LoanPayment_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "LoanPayment", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Model` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  model_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Model_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Model", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Product` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  product_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Product_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Product", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ProductTransfer` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  productTransfer_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ProductTransfer_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ProductTransfer", purpose: DELETE_MULTIPLE)
}
