# Loan Mutations

mutation createLoan(
  $id: String!
  $lenderName: String
  $borrowerName: String
  $totalAmount: Float!
  $paid: Float!
  $remaining: Float!
  $loanDate: String!
  $dueDate: String
  $type: String!
  $category: String!
  $status: String!
  $notes: String
  $bankId: String
  $bankName: String
  $employeeId: String
) @auth(level: PUBLIC) {
  loan_insert(
    data: {
      id: $id
      lenderName: $lenderName
      borrowerName: $borrowerName
      totalAmount: $totalAmount
      paid: $paid
      remaining: $remaining
      loanDate: $loanDate
      dueDate: $dueDate
      type: $type
      category: $category
      status: $status
      notes: $notes
      bankId: $bankId
      bankName: $bankName
      employeeId: $employeeId
    }
  )
}

mutation createLoanPayment(
  $id: String!
  $loanId: String!
  $amount: Float!
  $mode: String!
  $date: String!
  $bankId: String
  $bankName: String
) @auth(level: PUBLIC) {
  loanPayment_insert(
    data: {
      id: $id
      loanId: $loanId
      amount: $amount
      mode: $mode
      date: $date
      bankId: $bankId
      bankName: $bankName
    }
  )
}
